[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "kartify"
version = "0.1.0"
description = "A simple shopping cart library and CLI."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langgraph",
    "langchain",
    "langchain-core",
    "langchain-openai",
    "langchain-community",
    "grandalf",
    "pandas",
    "numpy",
    "python-dotenv",
]

[project.scripts]
kartify = "main:main"

[tool.setuptools]
py-modules = ["main"]

[tool.setuptools.packages.find]
where = ["src"]
